# https://taskfile.dev

version: '3'

dotenv: ['.env']

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true
  migrate:
    cmds:
      - migrate -path db/migrations -database "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=${POSTGRES_SSL_MODE}" {{.cmd}}
  create-migration:
    cmds:
      - migrate create -ext sql -dir db/migrations/ {{.name}} -tz UTC
  seed:
    cmds:
      # - go run ./cmd/bin/main.go seed -total={{.total}} -table={{.table}}
      - go run ./cmd/bin/main.go seed -table={{.table}}
  dev:
    cmds:
      - go run ./cmd/bin/main.go
  daemon:
    cmds:
      - pmgo
  ws:
    cmds:
      - go run ./cmd/bin/main.go ws --port=8080
  build:
    cmds:
      - go build -o ./marewo-app ./cmd/bin/main.go
  build-dev:
    cmds:
      - git pull
      - go build -o ./marewo-app ./cmd/bin/main.go
      - immortalctl stop marewo-dev
      # - immortalctl halt marewo-dev
      - mv ./marewo-app ../binaries/marewo-dev
      # - immortal -c ../binaries/marewo-dev/marewo-dev.yaml
      - immortalctl start marewo-dev
      - immortalctl status
  build-staging:
    cmds:
      - git pull
      - go build -o ./marewo-app ./cmd/bin/main.go
      - immortalctl stop marewo-staging
      # - immortalctl halt marewo-staging
      - mv ./marewo-app ../binaries/marewo-staging
      # - immortal -c ../binaries/marewo-staging/marewo-staging.yaml
      - immortalctl start marewo-staging
      - immortalctl status
  build-production:
    cmds:
      - git pull
      - go build -o ./marewo-app ./cmd/bin/main.go
      - immortalctl stop marewo-production
      # - immortalctl halt marewo-production
      - mv ./marewo-app ../binaries/marewo-production
      # - immortal -c ../binaries/marewo-production/marewo-production.yaml
      - immortalctl start marewo-production
      - immortalctl status
  lint-fix:
    cmds:
      - gofmt -w .
  lint-ci:
    cmds:
      - golangci-lint run
  nats:
    cmds:
      - nats-server --js
  commit:
    cmds:
      - task lint-fix
      - task lint-ci
      - git add .
      - git commit -m "{{.msg}}"
